apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-resource-policy-config.default
data:
  policy: |+
    ReservedResources:
      cpu: 750m
    #topology-aware:
    #  PinCPU: true
    #  PinMemory: true
    #  PreferIsolatedCPUs: true
    #  PreferSharedCPUs: false
  #logger: |+
    #Debug: resource-manager,cache,policy,resource-control
