apiVersion: v2
appVersion: main
description: |
  Topology-aware NRI resource policy plugin is a NRI plugin that will
  apply hardware-aware resource allocation policies to the containers
  running in the system.
name: nri-resource-policy-topology-aware
sources:
 - https://github.com/containers/nri-plugins
home: https://github.com/containers/nri-plugins
type: application
version: v0.0.0
