# Default values for memory-qos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
image:
  name: ghcr.io/containers/nri-plugins/nri-memtierd
  # tag, if defined will use the given image tag, otherwise Chart.AppVersion will be used
  #tag: unstable
  pullPolicy: Always

resources:
  cpu: 250m
  memory: 100Mi

outputDir: ""
